# Generated by Django 4.1.5 on 2023-01-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drums',
            options={'verbose_name_plural': 'Drums'},
        ),
        migrations.AlterField(
            model_name='drums',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
